<?php
$this->headScript()->appendFile($this->basePath() . '/js/admin/tinymce/tinymce.min.js');
$this->headScript()->appendScript("
    tinymce.init({
        force_br_newlines : true, force_p_newlines :false, forced_root_block : '',
        selector:'textarea',
        //removed_menuitems: 'cut, copy, paste',
        //removed_menus: 'file',
        block_formats: 'Paragraph=p;Header 1=h1;Header 2=h2;Header 3=h3;Header 4=h4;Header 5=h5;Header 6=h6',
        menubar: 'file edit insert',
        //menubar : false,
        paste_as_text: false,
        plugins:'autolink autosave autoresize lists link image charmap print preview searchreplace wordcount code visualblocks insertdatetime media save directionality textcolor colorpicker textpattern paste ',
        toolbar1: 'undo redo | bold italic underline superscript subscript strikethrough | removeformat | formatselect | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent forecolor backcolor | image media link unlink emoticons blockquote | preview | visualblocks | code',
        image_advtab: 'true',
        valid_elements: '@[title|style],a[href|target],h1,h2,h3,h4,h5,h6,hr,p,span,i,u,b,strong,em,sup,sub,ul,ol,li,blockquote,address,img[src|alt],video[controls|poster],source,iframe[src|width|height|allowfullscreen|frameborder]',
        paste_preprocess : function(pl, o) {
            var d = document.createElement('div');
            d.innerHTML = o.content;
            if(pl.clipboard.pasteFormat !== 'text') {
                o.content = d.innerText || d.text || d.textContent;
            }
        },
    });
    ");
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <?php echo $this->translate('Translations', 'csntranslation'); ?> <small><?php echo $this->translate('Edit', 'csntranslation'); ?></small>
        </h1>
        <ol class="breadcrumb">
            <li>
                <a href="<?php echo $this->url('admin-dashboard', array('action' => 'index')); ?>"><i class="fa fa-info"></i> <?php echo $this->translate('Dashboard', 'csntranslation'); ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('admin-translation', array('action' => 'index')); ?>"><i class="fa fa-language"></i> <?php echo $this->translate('Translations', 'csntranslation'); ?></a>
            </li>
            <li>
                <i class="fa fa-edit"></i> <?php echo $this->translate('Edit', 'csntranslation'); ?>
            </li>
        </ol>
    </div>
</div>
<?php
//$form = $this->form;
//$form->prepare();
//echo $this->form()->openTag($form);
//echo $this->formCollection($form);
//echo $this->form()->closeTag();


$form = $this->form;
$form->get('locale')->setAttributes(array(
    'class' => 'form-control',
    'id' => 'locale',
    //'disabled' => 'true',
    //'placeholder' => $this->translate('title', 'csntranslation')
));
$form->get('token')->setAttributes(array(
    'class' => 'form-control',
    'id' => 'token',
    //'readonly' => 'true'
    //'placeholder' => $this->translate('title', 'csntranslation')
));
$form->get('translation')->setAttributes(array(
    'class' => 'form-control',
    'id' => 'location',
    //'placeholder' => $this->translate('location', 'csntranslation')
));
$form->get('submit')->setAttributes(array(
    'method', 'post',
    'action', $this->url('admin-translation', array('controller' => 'translation', 'action' => 'edit')),
    'class' => 'btn btn-primary btn-lg btn-block',
    'value' => $this->translate('Edit', 'csntranslation')
));
$form->prepare();
?>
<div class="gap"></div>
<?php echo $this->form()->openTag($form); ?>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">

            <!-- message -->
            <?php if(isset($this->message)): ?>
                <div class="alert alert-danger">
                    <div class="text-center"><?php echo $this->message; ?></div>
                </div>
            <?php endif; ?>
            <?php $element = $form->get('csrf'); ?>
            <?php echo $this->formElement($element); ?>

            <!-- locale -->
            <?php $element = $form->get('locale'); ?>
            <?php $label =  $this->translate($element->getLabel(), 'csntranslation'); ?>
            <div class="form-group form-group-icon-left<?php echo ($this->formElementErrors($element) || isset($this->message))? ' has-error': null; ?>">
                <!-- <i class="fa fa-user input-icon input-icon-show"></i> -->
                <?php echo $this->formLabel($element, $label); ?>
                <?php echo $this->formElement($element); ?>
            </div>
            <?php echo $this->formElementErrors($element, array('class' => 'error-field')); ?>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">

            <!-- token -->
            <?php $element = $form->get('token'); ?>
            <?php $label =  $this->translate($element->getLabel(), 'csntranslation'); ?>
            <div class="form-group form-group-icon-left<?php echo ($this->formElementErrors($element) || isset($this->message))? ' has-error': null; ?>">
                <!-- <i class="fa fa-user input-icon input-icon-show"></i> -->
                <?php echo $this->formLabel($element, $label); ?>
                <?php echo $this->formElement($element); ?>
            </div>
            <?php echo $this->formElementErrors($element, array('class' => 'error-field')); ?>

            <!-- translation -->
            <?php $element = $form->get('translation'); ?>
            <?php $label =  $this->translate($element->getLabel(), 'csntranslation'); ?>
            <div class="form-group form-group-icon-left<?php echo ($this->formElementErrors($element) || isset($this->message))? ' has-error': null; ?>">
                <!-- <i class="fa fa-user input-icon input-icon-show"></i> -->
                <?php echo $this->formLabel($element, $label); ?>
                <?php echo $this->formElement($element); ?>
            </div>
            <?php echo $this->formElementErrors($element, array('class' => 'error-field')); ?>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4">

            <!-- submit -->
            <?php echo $this->formRow($form->get('submit')); ?>

        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>         
<div class="gap"></div>